import { ConvexReactClient } from "convex/react";

// Create a Convex client
export const convex = new ConvexReactClient(
  import.meta.env.VITE_CONVEX_URL || "http://127.0.0.1:3210"
);

// Export the API types - these will be generated by Convex
// Note: In a real setup, you'd typically have these types generated from your backend
// For now, we'll create a placeholder that matches what the frontend expects
export const api = {
  myFunctions: {
    analyzeSymptoms: "analyzeSymptoms" as const,
    getConversation: "getConversation" as const,
    createOrder: "createOrder" as const,
    cleanupDuplicateProfiles: "cleanupDuplicateProfiles" as const,
    createUserProfile: "createUserProfile" as const,
    getUserProfile: "getUserProfile" as const,
    updateUserProfile: "updateUserProfile" as const,
    getMedicines: "getMedicines" as const,
    getMedicineById: "getMedicineById" as const,
    getCartItems: "getCartItems" as const,
    addToCart: "addToCart" as const,
    updateCartItem: "updateCartItem" as const,
    removeFromCart: "removeFromCart" as const,
    getOrders: "getOrders" as const,
    createReminder: "createReminder" as const,
    getReminders: "getReminders" as const,
    updateReminder: "updateReminder" as const,
    deleteReminder: "deleteReminder" as const,
    createLabTest: "createLabTest" as const,
    getLabTests: "getLabTests" as const,
    updateLabTest: "updateLabTest" as const,
    getDoctors: "getDoctors" as const,
    getDoctorById: "getDoctorById" as const,
    createClinicalDoc: "createClinicalDoc" as const,
    getClinicalDocs: "getClinicalDocs" as const,
    getClinicalDocById: "getClinicalDocById" as const,
    getClinicalDocsByCategory: "getClinicalDocsByCategory" as const,
    getClinicalDocStats: "getClinicalDocStats" as const,
    updateClinicalDoc: "updateClinicalDoc" as const,
    deleteClinicalDoc: "deleteClinicalDoc" as const,
    seedClinicalDocs: "seedClinicalDocs" as const,
    createConversation: "createConversation" as const,
    getConversationById: "getConversationById" as const,
    addMessage: "addMessage" as const,
    createAppointment: "createAppointment" as const,
    getAppointments: "getAppointments" as const,
    updateAppointment: "updateAppointment" as const,
    generateUploadUrl: "generateUploadUrl" as const,
    getFileUrl: "getFileUrl" as const,
    viewer: "viewer" as const,
    // Add other function references as needed
  }
};
